hclivess/Bismuth

db.py
I really do request that you remove `pass`. I haven't done so because things are just a tad weird in this code-base :P
=> Minor pythonic improvements

balance_nogui.py
Make conditionals a bit more Pythonic. I'll be back for this one.
=> Minor improvement to readability

connections.py
Exceptions trapping and force cleanup of the socket poller in every case.
=> Cleanup of the socket poller

connections.py
Make sure each socket message is sent in one call, with nothing beetwen header and buffer.
Too soon to be 100% sure, but this may solve some connections issues.
=> Atomic send

connections.py, node.py
Tweaks to allow for more reliable and durable connections to the peers, including a "ping" command that does nothing but keep the socket and loop active.
=> Ping and more durable connections

node.py
In some situations (twice a day with some nodes) current code is banning good nodes for "consensus deviation too high".
It's happening because the consensus gets filled with way too old peers.
This proposal:
- corrects the trigger for banning a peer (there was a typo I think)
- does not add obviously late peers to the consensus
With this fix (in testing on several nodes that where often desync), consensus is way cleaner and close to 100%, and no good nodes are banned anymore.
=> Fixed banning of good nodes because of consensus deviation

commands.py
Optimize the code structure to increase the maintainability
=> change commands.py code and easier to maintain

node.py
mempool purge from old transactions that may be stuck.
once at start then every hour.
Also correction for a mempool dead lock.
Couldn't test right now, has to be tested. The sql I'm certain of however.
Should fix https://github.com/hclivess/Bismuth/issues/175
=> mempool cleaning and bugfix

requirements.txt
Updated with minimal modules needed for a fresh install
=> Up to date requirements.txt

requirements-node.txt
=> Requirements for a node only setup

node.py
Merged changes in latest node.py into the modular code.
I left many commented out lines on purpose, so devs can see what it was like before/after the change (globals => class).
They could be wiped after a while.
Needs merging before adding more changes to node.py or I'll have to meld and test again.
=> Merged new version into modular one.

send_nogui.py
Needed for Pools, exchanges...
=> Display Transaction ID when using send_nogui

log.py, node.py, wallet.py
Strange issue. Wallet relies on log_level WARNING.
Filtered logs bugs.
Quick fix here, root cause to id.
Related to default log level change in default config.txt.
More small edits to come in this pr
=> Fix wallet

essentials.py, mempool.py, node.py
Full separation of mempool related operations via dedicated module and class.
Use of a single connection object for all threads, with a lock() for write operations only.
Added status report.
=> Mempool module

apihandler.py
2 new api calls for pools:
- api_mempool, returns full mempool content
- api_clearmempool, empty mempool
Compatible with new mempool module and in memory mempool
=> Add mempool support

options.py
Some config params changed from 0/1 or yes/no to True/False.
This PR keeps the compatibility and allow for case differences.
=> Ensure compatibility with old files

node.py, plugins.py
Lightweight plugin system and first action hooks.
- block
- fullblock
- status
Many possible use, demo plugins and api doc coming soon on https://github.com/bismuthfoundation/BismuthPlugins
Needs this to be merged first.
=> Plugin support and first action hooks

ann.py, node.py
sql adjustements and a little pep
=> Small sql optimizations

wallet.py
added a support-collection button with absolute basic information. to be continued.
first step for better and faster help with light_wallet problems
=> added a support collection button

mempool.py
Fixed some bugs, 
Clarified the flow,
Very carefully simplified some bits,
Should improve merge speed and be easier to trace/debug.
Also added lowest priority to token operations.
Tested on my dev machine, but needs some more testing IRL to be sure.
=> Refactored mempool merge

mempool.py
Accept and auto fixes some wrongly formatted tx into mempool so they can be correctly synced with other nodes.
=> Add compatibility fix

node.py, tokensv2.py
Support for token hooks,
more info for block hooks
diff hook
as well as many small formatting tweaks
=> Token Hooks

node.py
- reworked digest_block - Will improve again later, didn't want to move too much at a time.
- preparing for finer logs selection
- faster tx digest
- added hooks on rollback and mined block
- added more info to current hooks
remerged with current 4.2.5.3 version to keep the latest improvements.
=> Faster transaction digestion and more

wallet.py
randomized light_ip-list, checked if 127.0.0.1 is present and if not, not added after shuffling the list. if yes, kept it in first position.
=> randomized light_ip-list

async_client.py, wallet_async.py
Refresh and connection task running in a threaded asyncio loop.
No more GUI freeze, faster ops via cached aliases and time selective sync.
Visual indication of the connected/disconnected status via the statusbar colour.
Could still need more work before a final release, So I renamed it to wallet_async.py
but should be merged as regular wallet.py asap after further tests and adjustments
=> Threaded Async version of the wallet

node.py
Trap and handle exceptions for "Transport endpoint is not connected".
=> Extra protection

aliases.py, ann.py, bisecdsa.py, bisprocmon.py
Use context managers to open and read files in such a way that the memory is freed as soon as possible.
=> Optimizations

balance_nogui.py, keygen.py
Change balance_nogui to use config file parameters.
Actually write out the private/public der for keygen.
=> Minor changes to keygen/balance_nogui

wallet_async.py
Easiest things first, this commit fixes the "logo.png" exception at L:1996. File changed to "logo.jpg".
=> Async Wallet Improvements

node.py
This PR is intended to update `node.py` so that we use context managers wherever feasible, make minor readability changes, so on and so forth. Please let me know if you have any qualms with this PR.
This PR supersedes https://github.com/hclivess/Bismuth/pull/299
=> Minor changes

node.py
- new hooks, see 105_rollback plugin in the plugin repo
- reverted wrongly used context manager in 3 define functions
- reverted some line splits that were making the code harder to read.
We all have widescreens now, we prefer one line a little too long than PEP wants, rather then 3 ugly tabbed lines.
sometimes readability is to be preferred to strict pep
=> Added some hooks for network log and analysis

node.py
Extra hooks to prepare for filtering of malicious actors.
=> Peer filtering hooks

node.py
On rollback request, for later use.
=> Add filter hook

async_client.py, lwbench.py, wallet_async.py
added logging to async_client rebenching, lwbench and added load balancing for wallet-servers based on client load in async wallet
=> added some logging, added client_load balancing

wallet.py
fixed missing app_log on wallet.py for benchmark
=> fixed missing app_log for benchmark

node.py
Some quick optis.
More can be done with subrequests but would require a little more testing and benchmarking.
The sql query for latest height is duped many times, would make sense to factorize in a global string.
=> SQL Optimization

connections.py, lwbench.py
reduced timeout for not answering servers on benchmark
=> fix for issue #326

commands.py, hmac_drbg.py, mining_heavy3.py, node.py, peershandler.py
=> Pre-release 4.2.7.0

mempool.py
https://github.com/hclivess/Bismuth/issues/334
=> Temp. Fix issue #334

node.py
(dup with above listlimjson, that does not work)
=> Reintroduce legacy listlim command

commands.py, node.py, options.py, peershandler.py, static/vacuum.sh
Post fork clean up
Peers new format compatibility tweaks and auto conversion
Testnet re-integration
Node init re-organized
Regnet first code
WIP, do not merge yet.
=> Work on post fork cleanup

commands.py, mempool.py, mining_heavy3.py, node.py, peershandler.py, regnet.py
New major functionality: Regtest mode.
Impacts many modules.
Isolated enough not to impact regular working of the node.
Do not merge yet, doc to come.
=> Regtest mode

lwbench.py, wallet.py
Tweaks to light wallet to use the new API and absorb more load.
=> Wallet update, for API use.

mempool.py
- Add mergedts timestamp to tx for better handling of late txs
- Quicker unfreeze
- Less strict freezing
=> Mempool tuning

send_nogui.py
Essentials interface change broke the script.
=> Fix send_nogui.py

peershandler.py
=> Use native values()
